Fix Python2 Support open encoding error
The Error:
$ sudo pip2 install retdec-python
File "/tmp/pip-build-35ctI4/retdec-python/setup.py", line 17, in read_file
        with open(file_path, encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

By using the io library we can use encodings in python 2 and 3 in the open function thus fixing the install for pip and python2.